class AppStrings {
  AppStrings._();
  static const String kAppTitle = 'HyperNym Internal Mobile App';
  static const String kAppTitleDrawer = 'HyperNym Internal \nMobile App';
  static const String kCompanyName = 'HyperNym';
  static const String kOr = 'OR';
  static const String kDuration = 'Duration';
  static const String kSignIn = 'Sign In';
  static const String kFaceIdLogIn = 'Login with Face ID';
  static const String kFaceIdAuth = "Face ID Authentication";
  static const String kSignUp = 'Sign Up';
  static const String kLogIn = 'Log In';
  static const String kLogOut = 'Log Out';
  static const String kLeaveType = 'Leave Type';
  static const String kViewProfile = 'View Profile';
  static const String done = "Done";
  static const String pending = "Pending";
  static const String kToolTip = 'Create new form';
  static const String kDeleteDialogue = 'Are you sure you want to delete?';
  static const String kTitle = 'Title';
  static const String kDate = 'Date';
  static const String kDescription = 'Description';
  static const String kVerifyEmail = "Verify email to continue";
  static const String kEmailSent = "We have sent a verification link to:";
  static const String kLogoutDialog = "Are you sure you want to logout?";
  static const String kDoNotHaveAcc = "Don't have an account?";
  static const String kEnterEmail = "Enter your email";
  static const String kEnterPassword = "Enter Password";
  static const String kYes = "Yes";
  static const String kSubmitApplication = "Submit Application";
  static const String kCancel = "Cancel";
  static const String kNo = "No";
  static const String kOk = "OK";
  static const String kUsername = "@username";
  static const String kEnterNumber = "Enter your phone number";
  static const String kConfirmPassword = "Confirm Password";
  static const String kLastName = "Last Name";
  static const String kFirstName = "First Name";
  static const String kUploadPic = "Upload Picture";
  static const String kUseFaceId = "Use Face ID to Login";
  static const String kUseFingerPrint = "Use Finger Print to Login";
  static const String kCamera = "Take Picture from Camera";
  static const String kGallery = "Select from Gallery";
  static const String kApplyLeave = "Apply Leave";
  static const String kApplyReimbursement = "Apply Expense Reimbursements";
  static const String kManageLeaves = "Manage Leaves";
  static const String kManageReimbursement = "Manage Reimbursements";
  static const String kMyName = "Huzaifa Zameer";
  static const String kApplyLeaveDesc =
      "Tap to apply leave and describe your issue well";
  static const String kApplyReimbursementDesc =
      "Tap to apply reimbursements and describe your issue well";
  static const String kManageLeavesDesc = "Tap to see leave applications";
  static const String kManageReimbursementDesc =
      "Tap to see reimbursement applications";
  static const String kLeavesSummary = "Leaves Summary";
  static const String kTotalLeaves = "Total Leaves";
  static const String kHi = "Hi,";
  static const String kAvailableLeaves = "Available Leaves";
  static const String kApplyLeaveHere = "Apply Your Leave Here";
  static const String kFrom = "From:";
  static const String kTo = "To:";
  static const String kManager = "Manager";
  static const String kSelectManager = "Select Your Manager";
  static const String kEmployeeName = "Employee name";
  static const String kApprovedBy = "Approved By";
  static const String kReason = "Reason";
}
